main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Materials
    url: /material/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Resources
    url: /resource/
    weight: 5

material:
  - name: Overview
    weight: 1
  - name: Lectures
    weight: 2
  - name: Readings
    weight: 2
assignment:
  - name: Assignments
    weight: 1
  - name: Final Project
    weight: 2
  - name: Lab
    weight: 4
  - name: Homework
    weight: 5
resource:
  - name: Resources
    weight: 1
  - name: Guides
    weight: 2
