main:
  - name: Register
    url: "https://www.eventbrite.com/e/women-in-data-science-conference-university-of-arizona-tickets-142036283347"
    weight: 1
  - name: Program
    url: /schedule/
    weight: 2
  - name: Speakers
    url: /sessions/
    weight: 3
  - name: "Code of Conduct"
    url: /conduct/
    weight: 4
  - name: "Sponsors and Organizers"
    url: /sponsors/
    weight: 5

sessions:
  - name: Keynote
    weight: 1
  - name: "Concurrent Speakers"
    weight: 2
  - name: "Data Blitz"
    weight: 3
  - name: Panels
    weight: 4
  - name: Networking
    weight: 5
sponsors:
  - name: Sponsors
    weight: 1
  - name: Organizers
    weight: 2
